import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/Navbar";
import React from "react";
import Footer from "@/app/Footer";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Portia Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
    <body className={`${inter.className} h-14 bg-gradient-to-r from-purple-500 to-pink-500`}>
    <Navbar/>
    {children}
    <Footer/>
    </body>
    </html>
  );
}
